### ISSUE TITLE
Peer To Peer Code Review - Morning Session 

### ISSUE THREAD

**Issue by JohnFTitor** [marilirulita/Leaderboard#4]
# Hello @marilirulita  👋🏻 

I have nothing to suggest. Your codebase is clean and readable 💯 💯. The functionality shares the same game with all the people that have the link, which is really cool! 😺 

Keep up the good pace. Happy coding!  🚀 

<img src="https://media2.giphy.com/media/fT3PPZwB2lZMk/giphy.gif"/>

**Comment by gabyse1** [comment]
### Hello @marilirulita
First of all, congratulations on your good job.
It is very organized and DRY.

I have nothing to suggest.

**Comment by oyelakinG9** [comment]
# Good job @marilirulita  ✔✔
Your code looks fine and clean  👍👍
There's nothing else to say than that.
Cheers and happy coding 👋👋

![](https://media.giphy.com/media/tIeCLkB8geYtW/giphy.gif)
